# Generate core/id_migration.gd from item_id_map.ps1 and skill_id_migration.ps1
$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
. (Join-Path $Root 'tools\item_id_map.ps1')
. (Join-Path $Root 'tools\skill_id_migration.ps1')

$lines = @(
    'class_name IdMigration',
    'extends RefCounted',
    '## PT to EN id maps for save migration (auto-generated by tools/gen_id_migration_gd.ps1).',
    '',
    'const ITEM_IDS := {'
)
foreach ($k in $itemIdMap.Keys | Sort-Object) {
    $v = $itemIdMap[$k]
    $lines += "	`"$k`": `"$v`","
}
$lines += '}'
$lines += ''
$lines += 'const SKILL_IDS := {'
foreach ($k in $skillIdMigration.Keys | Sort-Object) {
    $v = $skillIdMigration[$k]
    $lines += "	`"$k`": `"$v`","
}
$lines += '}'
$lines += ''
$lines += 'static func migrate_item_id(item_id: String) -> String:'
$lines += '	if item_id == "":'
$lines += '		return ""'
$lines += '	var base := item_id'
$lines += '	var suffix := ""'
$lines += '	var idx := item_id.rfind("_")'
$lines += '	if idx > 0:'
$lines += '		var tail := item_id.substr(idx + 1)'
$lines += '		if tail.is_valid_int() or tail.is_valid_float():'
$lines += '			base = item_id.substr(0, idx)'
$lines += '			suffix = item_id.substr(idx)'
$lines += '	return str(ITEM_IDS.get(base, base)) + suffix'
$lines += ''
$lines += 'static func migrate_skill_id(skill_id: String) -> String:'
$lines += '	if skill_id == "":'
$lines += '		return ""'
$lines += '	return str(SKILL_IDS.get(skill_id, skill_id))'

$out = Join-Path $Root 'core\id_migration.gd'
Set-Content -Path $out -Value ($lines -join "`n") -Encoding UTF8
Write-Host "Wrote $out"
