# Phase 1: English identifiers in active modules (.gd + .tscn)
$root = Split-Path $PSScriptRoot -Parent
$dirs = @('presentation', 'domains', 'data', 'platform', 'core', 'scenes', 'tests')
$extensions = @('*.gd', '*.tscn')

$renames = [ordered]@{
  # world_progress constants
  'TOTAL_MUNDOS' = 'TOTAL_WORLDS'
  'FASES_POR_MUNDO' = 'STAGES_PER_WORLD'
  'TOTAL_FASES' = 'TOTAL_STAGES'
  'PROGRESSO_COMPLETO' = 'FULL_PROGRESS'
  'HP_MULT_MUNDO' = 'HP_WORLD_MULT'
  'RECOMP_ESCALA' = 'REWARD_SCALE'
  'CHEFE_VIDA' = 'BOSS_HP_MULT'
  'CHEFE_DANO' = 'BOSS_DAMAGE_MULT'
  'POSICOES_FASES' = 'STAGE_POSITIONS'
  'MULTIPLICADORES' = 'MULTIPLIERS'
  'DANO_BASE' = 'DAMAGE_BASE'
  'DANO_ESCALA' = 'DAMAGE_SCALE'
  'DANO_EXPONENTE' = 'DAMAGE_EXPONENT'
  'INTERVALO_ATAQUE_INIMIGO' = 'ENEMY_ATTACK_INTERVAL'

  # skill_tree_definition constants
  'NUM_SECOES' = 'NUM_SECTIONS'
  'NUM_RAMOS' = 'NUM_BRANCHES'
  'NUM_LINHAS' = 'NUM_ROWS'
  'NOS_POR_SECAO' = 'NODES_PER_SECTION'
  'NOS_POR_RAMO' = 'NODES_PER_BRANCH'
  'TOTAL_NOS' = 'TOTAL_NODES'
  'LARGURA_COLUNA' = 'COLUMN_WIDTH'
  'ESPACO_COLUNAS' = 'COLUMN_GAP'
  'ALTURA_LINHA' = 'ROW_HEIGHT'
  'ALTURA_CABECALHO' = 'HEADER_HEIGHT'
  'OFFSET_LATERAL' = 'SIDE_OFFSET'
  'MARGEM_LATERAL' = 'SIDE_MARGIN'
  'MARGEM_SUPERIOR' = 'TOP_MARGIN'
  'MARGEM_INFERIOR' = 'BOTTOM_MARGIN'
  'CUSTO_BASE' = 'BASE_COST'
  'CUSTO_CRESCIMENTO' = 'COST_GROWTH'
  'CUSTO_POR_NIVEL' = 'COST_PER_LEVEL'
  'MULT_CUSTO_PREMIUM' = 'PREMIUM_COST_MULT'
  'NIVEL_MAX' = 'MAX_LEVEL'
  'NIVEL_MAX_ARMAZEM' = 'MAX_WAREHOUSE_LEVEL'
  '_PADRAO_LINHAS' = '_ROW_PATTERN'
  'NIVEIS_ITEM' = 'ITEM_LEVELS'

  # inventory / window constants
  'INVENTARIO_COLUNAS' = 'INVENTORY_COLUMNS'
  'INVENTARIO_LINHAS' = 'INVENTORY_ROWS'
  'TAMANHO_SLOT' = 'SLOT_SIZE'
  'ALTURA_JANELA' = 'WINDOW_HEIGHT'
  'ESPACO_RESERVADO_COMBATE' = 'COMBAT_RESERVED_SPACE'
  'TEXTO_SLOT_SKILL_VAZIO' = 'EMPTY_SKILL_SLOT_TEXT'
  'SLOTS_SINTSE' = 'SYNTHESIS_SLOTS'
  'TAMANHO_TOGGLE_ARMAZEM' = 'WAREHOUSE_TOGGLE_SIZE'
  'TEXTO_RODAPE' = 'FOOTER_TEXT'
  'TEXTO_DESMONTE' = 'DISMANTLE_TEXT'
  'TEXTO_JOIAS' = 'GEMS_TEXT'
  'TAMANHO_FASE' = 'STAGE_SIZE'
  'TAMANHO_CHEFE' = 'BOSS_SIZE'
  'POSICOES_TRILHA_FLORESTA' = 'FOREST_TRAIL_POSITIONS'
  'PALCO_MARGEM_TOPO' = 'STAGE_TOP_MARGIN'
  'PALCO_ALTURA' = 'STAGE_HEIGHT'
  'PAINEL_ALTURA' = 'PANEL_HEIGHT'
  'BOTAO_TAMANHO' = 'BUTTON_SIZE'
  'LARGURA_PAINEL_INVENTARIO' = 'INVENTORY_PANEL_WIDTH'
  'AVANCO_ATAQUE' = 'ATTACK_LUNGE'
  'DURACAO_AVANCO' = 'LUNGE_DURATION'
  'FRAME_SOLTA_FLECHA' = 'ARROW_RELEASE_FRAME'
  'COR_VIDA' = 'HP_COLOR'
  'LINHA_VOO' = 'FLIGHT_LINE'
  'BARRA_ARQUEIRO' = 'ARCHER_BAR'
  'JOGADORES_INICIAIS' = 'INITIAL_PLAYERS'
  'CAMINHO_AUDIO' = 'AUDIO_PATH'

  # skill_tree_definition enums
  'TipoBonus' = 'BonusType'
  'Secao' = 'Section'
  'ARMAZEM' = 'WAREHOUSE'

  # item_data enums (type names first)
  'AtributoGema' = 'GemAttribute'
  'ItemData.Tipo' = 'ItemData.Type'
  'enum Tipo' = 'enum Type'
  'ItemData.Raridade' = 'ItemData.Rarity'
  'enum Raridade' = 'enum Rarity'
  'ItemData.Categoria' = 'ItemData.Category'
  'enum Categoria' = 'enum Category'

  # item_data enum values - Type
  'Type.CAPACETE' = 'Type.HELMET'
  'Type.PEITORAL' = 'Type.CHEST'
  'Type.ARMA' = 'Type.WEAPON'
  'Type.SECUNDARIA' = 'Type.OFFHAND'
  'Type.LUVA' = 'Type.GLOVES'
  'Type.CALCA' = 'Type.PANTS'
  'Type.BOTA' = 'Type.BOOTS'
  'Type.CINTO' = 'Type.BELT'
  'Type.PINGENTE' = 'Type.PENDANT'
  'Type.ANEL' = 'Type.RING'
  'Type.BRACELETE' = 'Type.BRACELET'
  'Type.GEMA' = 'Type.GEM'
  'Tipo.CAPACETE' = 'Type.HELMET'
  'Tipo.PEITORAL' = 'Type.CHEST'
  'Tipo.ARMA' = 'Type.WEAPON'
  'Tipo.SECUNDARIA' = 'Type.OFFHAND'
  'Tipo.LUVA' = 'Type.GLOVES'
  'Tipo.CALCA' = 'Type.PANTS'
  'Tipo.BOTA' = 'Type.BOOTS'
  'Tipo.CINTO' = 'Type.BELT'
  'Tipo.PINGENTE' = 'Type.PENDANT'
  'Tipo.ANEL' = 'Type.RING'
  'Tipo.BRACELETE' = 'Type.BRACELET'
  'Tipo.GEMA' = 'Type.GEM'
  'Tipo.PET' = 'Type.PET'

  # GemAttribute values
  'GemAttribute.ATAQUE' = 'GemAttribute.ATTACK'
  'GemAttribute.ATAQUE_PCT' = 'GemAttribute.ATTACK_PCT'
  'GemAttribute.VIDA' = 'GemAttribute.HP'
  'GemAttribute.VIDA_PCT' = 'GemAttribute.HP_PCT'
  'GemAttribute.VEL_ATAQUE' = 'GemAttribute.ATTACK_SPEED'
  'GemAttribute.CRIT_DANO' = 'GemAttribute.CRIT_DAMAGE'
  'GemAttribute.EVASAO' = 'GemAttribute.EVASION'
  'GemAttribute.RES_FISICA' = 'GemAttribute.PHYS_RES'
  'GemAttribute.RES_ARCANA' = 'GemAttribute.ARCANE_RES'
  'GemAttribute.RES_ELEMENTAL' = 'GemAttribute.ELEMENTAL_RES'
  'AtributoGema.ATAQUE' = 'GemAttribute.ATTACK'
  'AtributoGema.VIDA' = 'GemAttribute.HP'

  # Rarity values
  'Rarity.COMUM' = 'Rarity.COMMON'
  'Rarity.INCOMUM' = 'Rarity.UNCOMMON'
  'Rarity.RARO' = 'Rarity.RARE'
  'Rarity.EPICO' = 'Rarity.EPIC'
  'Rarity.LENDARIO' = 'Rarity.LEGENDARY'
  'Rarity.MITICO' = 'Rarity.MYTHIC'
  'Raridade.COMUM' = 'Rarity.COMMON'
  'Raridade.INCOMUM' = 'Rarity.UNCOMMON'

  # Category values
  'Category.EQUIPAMENTO' = 'Category.EQUIPMENT'
  'Category.ACESSORIO' = 'Category.ACCESSORY'
  'Category.GEMA' = 'Category.GEM'
  'Categoria.EQUIPAMENTO' = 'Category.EQUIPMENT'

  # BonusType values
  'BonusType.ATAQUE' = 'BonusType.ATTACK'
  'BonusType.ATAQUE_PCT' = 'BonusType.ATTACK_PCT'
  'BonusType.VIDA' = 'BonusType.HP'
  'BonusType.BONUS_XP' = 'BonusType.XP_BONUS'
  'BonusType.BONUS_OURO' = 'BonusType.GOLD_BONUS'
  'BonusType.VEL_ATAQUE' = 'BonusType.ATTACK_SPEED'
  'BonusType.CRIT_DANO' = 'BonusType.CRIT_DAMAGE'
  'BonusType.EVASAO' = 'BonusType.EVASION'
  'BonusType.RES_FISICA' = 'BonusType.PHYS_RES'
  'BonusType.RES_ARCANA' = 'BonusType.ARCANE_RES'
  'BonusType.RES_ELEMENTAL' = 'BonusType.ELEMENTAL_RES'
  'TipoBonus.ATAQUE' = 'BonusType.ATTACK'
  'TipoBonus.VIDA' = 'BonusType.HP'

  # Section enum values
  'Section.ATAQUE' = 'Section.ATTACK'
  'Section.DEFESA' = 'Section.DEFENSE'
  'Section.UTILIDADE' = 'Section.UTILITY'
  'enum Secao' = 'enum Section'
  'Secao.' = 'Section.'
  'Secao.ATAQUE' = 'Section.ATTACK'

  # item_data exports / fields

  # enemy fields
  'var vida_maxima:' = 'var max_hp:'
  'var vida_atual:' = 'var current_hp:'
  'var ouro_recompensa:' = 'var gold_reward:'
  'var xp_recompensa:' = 'var xp_reward:'
  'vida_maxima' = 'max_hp'
  'vida_atual' = 'current_hp'
  'ouro_recompensa' = 'gold_reward'
  'xp_recompensa' = 'xp_reward'
  'p_vida' = 'p_hp'
  'p_ouro' = 'p_gold'

  # skill_tree_definition functions
  'pais_do_slot' = 'parent_slots'
  'slots_da_linha' = 'slots_in_row'
  'linha_do_slot' = 'slot_row'
  'coluna_do_slot' = 'slot_column'
  'custo_proximo_nivel' = 'next_level_cost'
  'valor_bonus' = 'bonus_value'
  'nome_proximo_nivel' = 'next_level_name'
  'cor_regiao' = 'region_color'
  'nome_regiao' = 'region_name'
  'chave_bonus' = 'bonus_key'
  'bonus_vazio' = 'empty_bonus'
  'id_do_no' = 'node_id'
  '_criar_def_no' = '_create_node_def'
  '_criar_no_ataque' = '_create_attack_node'
  '_criar_no_defesa' = '_create_defense_node'
  '_criar_no_utilidade' = '_create_utility_node'
  '_montar_def_stat' = '_build_stat_def'
  '_valor_por_tipo' = '_value_for_type'

  # item_data functions
  'nome_atributo_gema' = 'gem_attribute_name'
  'valor_base_gema' = 'base_gem_value'
  'calcular_valor_gema' = 'calculate_gem_value'
  'criar_gema' = 'create_gem'
  'normalizar_nivel_item' = 'normalize_item_level'
  'indice_nivel_item' = 'item_level_index'
  'multiplicador_nivel_item' = 'item_level_multiplier'
  'nivel_item_maximo' = 'max_item_level'
  'sortear_nivel_item' = 'roll_item_level'
  'cor_de_raridade' = 'rarity_color'
  'nomes_filtro_ferraria' = 'forge_filter_names'
  'nivel_heroi' = 'hero_level'

  # presentation functions
  'configurar_botao_icone' = 'setup_icon_button'
  'ordenar_slots' = 'sort_slots'
  '_reforcar_layout' = '_enforce_layout'
  '_adicionar_linha' = '_add_row'
  '_centralizar' = '_center_view'
  '_tamanho_no' = '_node_size'
  '_paint_button' = '_style_button'
  '_paint_stage' = '_style_stage'
  'exibir' = 'show_damage'
  'disparar' = 'fire'
  '_voar' = '_fly'
  '_obter_frames' = '_get_frames'
  '_carregar_sheet' = '_load_sheet'
  'escala' = 'scale_for'
  'barra_offset' = 'health_bar_offset'
  '_montar_arqueiro' = '_build_archer'
  '_carregar_textura' = '_load_texture'
  '_ler_json' = '_read_json'
  'esmaecer' = 'fade_out'
  '_animar_preenchimento' = '_animate_fill'
  '_frames_padrao' = '_default_frames'
  '_pose_texture' = '_pose_texture'
  'alinhar' = 'align_panel'
  'largura_janela' = 'window_width'
  '_posicionar_lado' = '_position_side'
  '_sobrepor_painel' = '_overlay_panel'
  '_paint_tab' = '_style_tab'

  # audio
  '_som_dano' = '_damage_sound'

  # party / combat params
  'nova_classe' = 'new_class'
  'quantidade' = 'amount'
  'caido' = 'fallen'
  'resetar' = 'reset_hp'
  '_timer_inimigo' = '_enemy_timer'
  'novo_mundo' = 'new_world'
  'nova_fase' = 'new_stage'
  'nova_dificuldade' = 'new_difficulty'

  # worlds panel state
  '_mundo_aberto' = '_world_menu_open'
  '_mundo_atual' = '_current_world'
  '_fase_atual' = '_current_stage'
  '_liberadas' = '_unlocked'
  '_botoes_mundo' = '_world_buttons'
  '_botoes_fase' = '_stage_buttons'
  '_rotulos_fase' = '_stage_labels'
  '_ancoras_fase' = '_stage_anchors'
  '_tex_fase' = '_stage_tex'
  '_tex_chefe' = '_boss_tex'
  'fundo_menu_dificuldade' = 'difficulty_menu_backdrop'
  'fundo_mapa' = 'map_background'
  'mapa_fases' = 'stage_map'
  'lista_mundos' = 'world_list'
  'botao_dificuldade' = 'difficulty_button'
  'opcoes_dificuldade' = 'difficulty_options'
  'menu_dificuldade' = 'difficulty_menu'
  'painel_lista' = 'list_panel'
  'painel_mapa' = 'map_panel'
  'botao_voltar' = 'back_button'

  # inventory @onready vars
  'botao_ordenar_inventario' = 'sort_inventory_button'
  'botao_sair' = 'exit_button'
  'botao_sair_jogo' = 'quit_game_button'
  'botao_configuracoes' = 'settings_button'
  'painel_configuracoes' = 'settings_panel'
  'botao_fechar_config' = 'close_settings_button'
  'grade_inventario' = 'inventory_grid'
  'nome_personagem' = 'character_name_label'
  'nivel_personagem' = 'character_level_label'
  'foto_personagem' = 'character_portrait'
  'linha_card_heroi' = 'hero_card_row'
  'barra_xp_personagem' = 'character_xp_bar'
  'label_xp_personagem' = 'character_xp_label'
  'botao_atributos_personagem' = 'character_attributes_button'
  'secao_heroi_visual' = 'hero_visual_section'
  'host_botao_formacao' = 'formation_button_host'
  'ui_equipe' = 'team_ui'
  'area_menus' = 'menu_area'
  'painel_ferraria' = 'forge_panel_node'
  'painel_armazem' = 'warehouse_panel_node'
  'painel_mundos' = 'worlds_panel_node'
  'painel_formacao' = 'formation_panel_node'
  'painel_skills' = 'skills_panel_node'
  'painel_atributos' = 'attributes_panel_node'
  'painel_arvore' = 'skill_tree_panel_node'
  'botao_ferraria' = 'forge_button'
  'botao_armazem' = 'warehouse_button'
  'botao_mundo' = 'world_button'
  'label_ouro' = 'gold_label'
  'painel_ouro' = 'gold_panel'
  'espaco_ouro' = 'gold_spacer'
  'centralizar' = 'center_anchor'  # .gd only; tscn uses CenterAnchor via $tscnRenames
  'grade_personagens' = 'character_row'
  'equip_esquerda' = 'equip_left'
  'equip_direita' = 'equip_right'
  'coluna_ativas' = 'active_column'
  'coluna_passivas' = 'passive_column'
  'area_botao_menu' = 'menu_button_area'
  'label_dano' = 'damage_label'

  # forge panel
  'grade_sintese' = 'synthesis_grid'
  'grade_desmontar' = 'dismantle_grid'
  'botao_preenchimento' = 'autofill_button'
  'botao_info_nivel' = 'level_info_button'
  'toggle_armazem' = 'warehouse_toggle'
  'toggle_trilho' = 'toggle_track'
  'toggle_knob' = 'toggle_knob'
  'botao_sintetizar' = 'synthesize_button'
  'botao_desmontar' = 'dismantle_button'
  'botao_aba_sintese' = 'synthesis_tab_button'
  'botao_aba_desmontar' = 'dismantle_tab_button'
  'botao_aba_joias' = 'gems_tab_button'
  'botao_filtro_forja' = 'forge_filter_button'
  'botao_preenchimento_desmonte' = 'dismantle_autofill_button'
  'botao_filtro_desmonte' = 'dismantle_filter_button'
  'painel_sintese' = 'synthesis_panel'
  'painel_desmontar' = 'dismantle_panel'
  'painel_joias' = 'gems_panel'
  'area_joias' = 'gems_area'
  'botao_imbuir' = 'imbue_button'
  'label_explicacao' = 'explanation_label'
  'label_explicacao_desmontar' = 'dismantle_explanation_label'
  'label_explicacao_joias' = 'gems_explanation_label'
  'label_valor_desmonte' = 'dismantle_value_label'
  'corpo_ferraria' = 'forge_body'

  # other panels
  'slots_equipe' = 'party_slots'
  'rolagem_herois' = 'hero_scroll'
  'grade_herois' = 'hero_grid'
  'label_dica' = 'hint_label'
  'slots_heroi' = 'hero_slots'
  'label_skills_heroi' = 'hero_skills_label'
  'sessao_equipadas' = 'equipped_section'
  'sessao_ativas' = 'active_section'
  'sessao_passivas' = 'passive_section'
  'grade_equip_ativas' = 'equipped_active_grid'
  'grade_equip_passivas' = 'equipped_passive_grid'
  'grade_ativas' = 'active_grid'
  'grade_passivas' = 'passive_grid'
  'grade_armazem' = 'warehouse_grid'
  'label_status' = 'status_label'
  'botao_ordenar' = 'sort_button'
  'linha_abas' = 'tab_row'
  'titulo_equipe' = 'party_title'
  'titulo_classes' = 'classes_title'
  'botao_formacao' = 'formation_button'
  'label_mensagem' = 'message_label'
}

$tscnRenames = [ordered]@{
  'BotaoOrdenarInventario' = 'SortInventoryButton'
  'BotaoSair' = 'ExitButton'
  'BotaoSairJogo' = 'QuitGameButton'
  'BotaoConfiguracoes' = 'SettingsButton'
  'PainelConfiguracoes' = 'SettingsPanel'
  'BotaoFecharConfig' = 'CloseSettingsButton'
  'GradeInventario' = 'InventoryGrid'
  'NomePersonagem' = 'CharacterNameLabel'
  'NivelPersonagem' = 'CharacterLevelLabel'
  'FotoPersonagem' = 'CharacterPortrait'
  'LinhaCardHeroi' = 'HeroCardRow'
  'BarraXpPersonagem' = 'CharacterXpBar'
  'LabelXpPersonagem' = 'CharacterXpLabel'
  'BotaoAtributosPersonagem' = 'CharacterAttributesButton'
  'SecaoHeroiVisual' = 'HeroVisualSection'
  'HostBotaoFormacao' = 'FormationButtonHost'
  'AreaEquipe' = 'TeamArea'
  'AreaMenus' = 'MenuArea'
  'BotaoArmazem' = 'WarehouseButton'
  'BotaoMundo' = 'WorldButton'
  'LabelOuro' = 'GoldLabel'
  'PainelOuro' = 'GoldPanel'
  'EspacoOuro' = 'GoldSpacer'
  'Centralizar' = 'CenterAnchor'
  'GradePersonagens' = 'CharacterRow'
  'EquipEsquerda' = 'EquipLeft'
  'EquipDireita' = 'EquipRight'
  'ColunaAtivas' = 'ActiveColumn'
  'ColunaPassivas' = 'PassiveColumn'
  'LabelInimigo' = 'EnemyLabel'
  'BarraVidaInimigo' = 'EnemyHealthBar'
  'LabelNivel' = 'LevelLabel'
  'LabelDano' = 'DamageLabel'
  'BotaoRepetirFase' = 'RepeatStageButton'
  'LabelAviso' = 'NoticeLabel'
  'Chao' = 'Floor'
  'InimigoVisual' = 'EnemyVisual'
  'CamadaEfeitos' = 'EffectsLayer'
  'PainelBatalha' = 'BattlePanel'
  'Palco' = 'StageArea'
  'AreaBotaoMenu' = 'MenuButtonArea'
  'BotaoAbrirInventario' = 'OpenInventoryButton'
  'HudInventario' = 'InventoryHud'
  'HudBatalha' = 'BattleHud'
  'HudBotao' = 'ButtonHud'
  'BotaoVoltarArvore' = 'SkillTreeBackButton'
  'LabelOuroArvore' = 'SkillTreeGoldLabel'
  'LabelMensagemArvore' = 'SkillTreeMessageLabel'
  'CabecalhoArvore' = 'SkillTreeHeader'
  'BotaoFecharSkills' = 'CloseSkillsButton'
  'CabecalhoSkills' = 'SkillsHeader'
  'SlotsHeroiSkills' = 'HeroSkillSlots'
  'LabelSkillsHeroi' = 'HeroSkillsLabel'
  'SessaoEquipadas' = 'EquippedSection'
  'SessaoAtivas' = 'ActiveSkillsSection'
  'SessaoPassivas' = 'PassiveSkillsSection'
  'BotaoFecharFormacao' = 'CloseFormationButton'
  'CabecalhoFormacao' = 'FormationHeader'
  'SlotsFormacao' = 'FormationSlots'
  'RolagemHerois' = 'HeroScroll'
  'GradeHeroisFormacao' = 'FormationHeroGrid'
  'LabelDicaFormacao' = 'FormationHintLabel'
  'BotaoVoltarMundos' = 'WorldsBackButton'
  'BotaoFecharMundos' = 'CloseWorldsButton'
  'TituloMundos' = 'WorldsTitle'
  'CabecalhoMundos' = 'WorldsHeader'
  'PainelListaMundos' = 'WorldListPanel'
  'ListaMundos' = 'WorldList'
  'BotaoDificuldade' = 'DifficultyButton'
  'OpcoesDificuldade' = 'DifficultyOptions'
  'MenuDificuldade' = 'DifficultyMenu'
  'FundoMenuDificuldade' = 'DifficultyMenuBackdrop'
  'FundoMapa' = 'MapBackground'
  'TituloEquipe' = 'PartyTitle'
  'TituloClasses' = 'ClassesTitle'
  'SlotsEquipe' = 'PartySlots'
  'BotaoFormacao' = 'FormationButton'
  'ListaAtributos' = 'AttributesList'
  'BotaoVoltarAtributos' = 'AttributesBackButton'
  'CabecalhoAtributos' = 'AttributesHeader'
  'CabecalhoArmazem' = 'WarehouseHeader'
  'BotaoFecharArmazem' = 'CloseWarehouseButton'
  'BotaoOrdenarArmazem' = 'SortWarehouseButton'
  'LabelStatusArmazem' = 'WarehouseStatusLabel'
  'GradeArmazem' = 'WarehouseGrid'
}

function Apply-Renames($files, $map) {
  $ordered = $map.Keys | Sort-Object { $_.Length } -Descending
  foreach ($file in $files) {
    $text = [IO.File]::ReadAllText($file.FullName)
    $orig = $text
    foreach ($old in $ordered) {
      $new = $map[$old]
      if ($old -eq $new) { continue }
      if ($old -match '^[A-Za-z_][A-Za-z0-9_]*$') {
        $text = [regex]::Replace($text, "(?<![A-Za-z0-9_])$old(?![A-Za-z0-9_])", $new)
      } else {
        $text = $text.Replace($old, $new)
      }
    }
    if ($text -ne $orig) {
      [IO.File]::WriteAllText($file.FullName, $text)
      Write-Host $file.FullName.Replace($root + '\', '')
    }
  }
}

$allFiles = @()
foreach ($dir in $dirs) {
  $base = Join-Path $root $dir
  if (-not (Test-Path $base)) { continue }
  $allFiles += Get-ChildItem $base -Recurse -Include $extensions
}

Apply-Renames ($allFiles | Where-Object { $_.Extension -eq '.gd' }) $renames
Apply-Renames $allFiles $tscnRenames
Write-Host 'Phase 1 code rename complete.'
